ARG IMAGE_NAME=dustynv/ros:humble-pytorch-l4t-r35.1.0

FROM ${IMAGE_NAME}

ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=0
ARG ZED_SDK_PATCH=7
ARG L4T_MAJOR=35
ARG L4T_MINOR=1

ARG ROS2_DIST=humble

ENV QT_X11_NO_MITSHM=1
ENV EDITOR=nano
ENV XDG_RUNTIME_DIR=/tmp
ENV ROS_DOMAIN_ID=42

# Disable apt-get warnings
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 42D5A192B819C5DA || true && \
  apt-get update || true && apt-get install -y --no-install-recommends apt-utils dialog && \
  rm -rf /var/lib/apt/lists/*
  
ENV TZ=Europe/Paris

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \ 
  apt-get update && \
  apt-get install --yes lsb-release wget less udev sudo build-essential cmake python3 python3-dev python3-pip python3-wheel git jq libpq-dev zstd usbutils && \    
  rm -rf /var/lib/apt/lists/*

# YOLOv5 requirements ------------------------------------------------------------------------

#From Ultralytic NVIDIA Jetson Nano Deployment
RUN sudo apt update
RUN sudo apt install -y python3-pip 
RUN pip3 install --upgrade pip   
RUN sudo apt install -y libfreetype6-dev

#From Yolov5 requirements.txt
RUN pip3 install setuptools>=65.5.1 # Snyk vulnerability fix
RUN pip3 install gitpython>=3.1.30
RUN pip3 install matplotlib>=3.3
RUN pip3 install numpy>=1.23.5
RUN pip3 install Pillow>=9.4.0
RUN pip3 install psutil  # system resources
RUN pip3 install PyYAML>=5.3.1
RUN pip3 install requests>=2.23.0
RUN pip3 install scipy>=1.4.1
RUN pip3 install thop>=0.1.1  # FLOPs computation
RUN pip3 install tqdm>=4.64.0
RUN pip3 install ultralytics==8.0.232 --no-deps # nodeps to avoid opencv overwrite
RUN pip3 install cycler --no-deps
RUN pip3 install kiwisolver --no-deps
RUN pip3 install pandas>=1.1.4
RUN pip3 install seaborn>=0.11.0

#From old versions of this image
RUN pip3 install numpy-quaternion
RUN pip3 install utm


# Needed to work with pyzed on ARM
ENV OPENBLAS_CORETYPE=ARMV8


WORKDIR /home/asv_ai_workspace
COPY ./asv_ai_workspace /home/asv_ai_workspace



COPY ros_entrypoint_jetson.sh /sbin/ros_entrypoint.sh
RUN sudo chmod 755 /sbin/ros_entrypoint.sh


CMD ["bash"]