ARG IMAGE_NAME=dustynv/ros:humble-ros-base-l4t-r35.1.0
FROM ${IMAGE_NAME}

RUN apt-get update && \
    apt-get install -y \
        git \
        python3-opencv \
        libglib2.0-0


ENV QT_X11_NO_MITSHM=1
ENV EDITOR=nano
ENV XDG_RUNTIME_DIR=/tmp
ENV ROS_DOMAIN_ID=42

RUN apt-get update && apt-get install -y \
    cmake \
    curl \
    nano \
    python3-pip \
    python3-pydantic \
    ruby-dev \
    wget \
    xorg-dev \
    iputils-ping 

RUN pip3 install setuptools==58.2.0

RUN pip3 install utm
RUN pip3 install numpy-quaternion
RUN pip3 install -U ultralytics

# Install additional dependencies
RUN apt-get update && \
    apt-get install -y \
        git \
        python3-opencv \
        libglib2.0-0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PyTorch
RUN python3 -m pip install torch==1.10.0 torchvision==0.11.1 -f https://download.pytorch.org/whl/cu114.html

# Create a symbolic link for libv4l2.so
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so /usr/lib/aarch64-linux-gnu/libv4l2.so

# Set environment variable for OpenBLAS_CORETYPE
ENV OPENBLAS_CORETYPE=ARMV8

# Set working directory and copy workspace
WORKDIR /home/asv_ai_workspace
COPY ./asv_ai_workspace /home/asv_ai_workspace

# # Source ROS 2 setup file
# RUN /bin/bash -c "source /opt/ros/humble/install/setup.bash"

# Setup environment variables
CMD ["bash"]